services:
   react-todo:
     container_name: react-todo
     build:
       context: ./react-todo
       dockerfile: Dockerfile
     volumes:
       - ./react-todo:/app
       - /app/node_modules
     ports:
       - "3002:3000"
     environment:
       - CHOKIDAR_USEPOLLING=true

   api:
     build:
       context: ./api
       dockerfile: Dockerfile
     ports:
       - "8080:8080"
     volumes:
       - ./api:/app

   mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
