services:
  react-todo:
    container_name: react-todo
    build:
      context: ./react-todo
      dockerfile: Dockerfile
    volumes:
      - ./react-todo:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app