# .air.toml
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

[build]
cmd = "go build -o ./tmp/main ./cmd"
bin = "tmp/main"
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"

[watch]
include_ext = ["go"]
# Ignore these filename extensions or directories.
exclude_dir = ["test"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color is found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = "white"

[misc]
# Delete binary after Air has done.
clean = true